resolver: lts-22.12
compiler: ghc-9.4.8

packages:
- .

extra-deps:
- git: https://github.com/tianyaochou/hakyll-ede
  commit: 0896515e7cbad24564e38a7af4f3e35bb5fa3991
- git: https://github.com/brendanhay/ede
  commit: 041ef0b8bc273eb16da167716bc60337d7fcfaa1
- aeson-2.2.1.0
- attoparsec-aeson-2.2.0.1

nix:
  enable: true
  packages: [ zlib pkg-config ]
